#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/merryyou-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6380

#端口
server:
  port: 8060
  session:
    timeout: 600 #session失效时间

#security
security:
  basic:
    enabled: true
#  oauth2:
#    client:
#      clientId: merryyou
#      clientSecret: merryyousecret

#自定义登录页面
merryyou:
  security:
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
#      loginPage: /demo-signIn.html #自定义登陆界面
#      loginType: REDIRECT
#    code:
#      image:
#        length: 6  #验证码长度
#        width: 100  #验证码宽度
#        url: /user,/user/* #验证码拦截的url
#    social:
#      qq:
#        app-id:
#        app-secret:
#        providerId: callback.do
#      weixin:
#        app-id:
#        app-secret:
#      filterProcessesUrl: /qqLogin
#    oauth2:
#      clients[0]:
#        clientId: merryyou
#        clientSecret: merryyousecret
#        accessTokenValiditySeconds: 7200
